### ISSUE TITLE
Review Multiple MIPs 

### ISSUE THREAD

**Issue by windauer** [betterFORM/betterFORM#19]
DeclarationViewImpl suddenly has a list of constrains and(!) a single constraint. In ConstraintVertex only the constraints list was evaluated but not the single constraint (which resulted in an error that is now fixed). 

There should be no parallel single constraint and multiple constraint handling at all. Proposal: only use the constraints list and remove reference to the single constraint. Review all other MultipleMips changes if they are issues as well.

**Comment by JoernT** [comment]
the change was a misunderstanding of the original functionality. Change has been rolled back and testcase has been fixed. 

However the API is still not very clean and should be refactored to just use the constraint list instead of the single constraint in DeclarationView - the getter and setter should be removed from the interface.

**Comment by windauer** [comment]
Ticket was moved to http://betterform.myjetbrains.com/youtrack/issue/bf-31
